src/Entity/Article.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[Vich\Uploadable]
#[ApiResource()]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $Titre = null;

    #[ORM\Column(length: 600, nullable: true)]
    private ?string $resume = null;

    #[Vich\UploadableField(mapping: 'article_images', fileNameProperty: 'image', size: 'imageSize')]
    #[Assert\Image]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $image = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(?string $resume): static
    {
        $this->resume = $resume;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/EvenementsController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class EvenementsController extends AbstractController
{
    #[Route('/evenements', name: 'app_evenements')]
    public function index(ArticleRepository $repository): Response
    {
        $articles = $repository->findAll();

        return $this->render('evenements/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    #[Route('/evenements/affiche', name: 'app_affiche')]
    public function affiche(ArticleRepository $repository): Response
    {
        $articles = $repository->findByCategory(1);

        return $this->render('evenements/affiche.html.twig', [
            'articles' => $articles,
        ]);
    }

    #[Route('/evenements/rubrique', name: 'app_rubrique')]
    public function rubrique(ArticleRepository $repository): Response
    {
        $articles = $repository->findByCategory(2);

        return $this->render('evenements/rubrique.html.twig', [
            'articles' => $articles,
        ]);
    }
}

templates/evenements/affiche.html.twig
{% extends 'base.html.twig' %} {% block title %}Évenements{% endblock %} {% block
body %} {% include "header/header.html.twig" %} 
<div class="bg-gray-900 font-Trykker">
  <div class="flex justify-center mt-4 pb-4">
    <h3 class="rounded-lg shadow border-8 bg-gray-800 border-gray-800 text-white mx-2">Actualités et concerts à venir concernant la Cantarella</h3>
  </div>
  <div class="flex justify-center">
    <a class="border-gray-800 bg-gray-800 rounded-lg shadow border-8 text-white mx-2 hover:border-gray-700 hover:bg-gray-700" href="{{ path('app_evenements') }}">Tout afficher</a>
    <a class="border-gray-800 bg-gray-800 rounded-lg shadow border-8 text-white mx-2 hover:border-gray-700 hover:bg-gray-700" href="{{ path('app_rubrique') }}">Trier par rubrique</a>
  </div>
<div class="flex justify-around pt-8 mb-8 max-[480px]:flex-col flex-wrap items-center">
  {% for article in articles %}
  <div class="max-w-sm rounded-lg shadow bg-gray-800 border-gray-700 p-2 mx-2 max-[480px]:mb-8 mb-4">
    <h5
      class="mb-2 text-2xl font-bold tracking-tight text-white"
    >
      {{ article.titre | raw }} 
      {# striptags for the ... #}
    </h5>
    <div class="p-5 border-t-2 border-t-gray-950">
      <img class="rounded-t-lg" src="{{ vich_uploader_asset(article) }}" />
      <p class="mb-3 font-normal text-gray-400">
        <div class="border-t-2 border-t-gray-950 text-gray-400">
        {{ article.resume | raw }}
        </div>
      </p>
    </div>
  </div>
  {% endfor %}
</div>
</div>
{% include "footer/footer.html.twig" %} {% endblock %}

templates/evenements/index.html.twig
{% extends 'base.html.twig' %} {% block title %}Évenements{% endblock %} {% block
body %} {% include "header/header.html.twig" %} 
<div class="bg-gray-900 font-Trykker">
  <div class="flex justify-center mt-4 pb-4">
  <h3 class="rounded-lg shadow border-8 bg-gray-800 border-gray-800 text-white mx-2">Actualités et concerts à venir concernant la Cantarella</h3>
</div>
<div class="flex justify-center">
  <a class="border-gray-800 bg-gray-800 rounded-lg shadow border-8 text-white mx-2 hover:border-gray-700 hover:bg-gray-700" href="{{ path('app_affiche') }}">Trier par affiche</a>
  <a class="border-gray-800 bg-gray-800 rounded-lg shadow border-8 text-white mx-2 hover:border-gray-700 hover:bg-gray-700" href="{{ path('app_rubrique') }}">Trier par rubrique</a>
</div>
<div class="flex justify-around pt-8 mb-8 max-[480px]:flex-col flex-wrap items-center">
  {% for article in articles %}
  <div class="max-w-sm rounded-lg shadow bg-gray-800 border-gray-700 p-2 mx-2 max-[480px]:mb-8 mb-4">
    <h5
      class="mb-2 text-2xl font-bold tracking-tight text-white"
    >
      {{ article.titre | raw }} 
      {# striptags for the ... #}
    </h5>
    <div class="p-5 border-t-2 border-t-gray-950">
      <img class="rounded-t-lg" src="{{ vich_uploader_asset(article) }}" />
      <p class="mb-3 font-normal text-gray-400">
        <div class="border-t-2 border-t-gray-950 text-gray-400">
        {{ article.resume | raw }}
        </div>
      </p>
    </div>
  </div>
  {% endfor %}
</div>
</div>
{% include "footer/footer.html.twig" %} {% endblock %}

templates/evenements/rubrique.html.twig
{% extends 'base.html.twig' %} {% block title %}Évenements{% endblock %} {% block
body %} {% include "header/header.html.twig" %} 
<div class="bg-gray-900 font-Trykker">
  <div class="flex justify-center mt-4 pb-4">
    <h3 class="rounded-lg shadow border-8 bg-gray-800 border-gray-800 text-white mx-2">Actualités et concerts à venir concernant la Cantarella</h3>
  </div>
  <div class="flex justify-center">
    <a class="border-gray-800 bg-gray-800 rounded-lg shadow border-8 text-white mx-2 hover:border-gray-700 hover:bg-gray-700" href="{{ path('app_evenements') }}">Tout afficher</a>
    <a class="border-gray-800 bg-gray-800 rounded-lg shadow border-8 text-white mx-2 hover:border-gray-700 hover:bg-gray-700" href="{{ path('app_affiche') }}">Trier par affiche</a>
  </div>
<div class="flex justify-around pt-8 mb-8 max-[480px]:flex-col flex-wrap items-center">
  {% for article in articles %}
  <div class="max-w-sm rounded-lg shadow bg-gray-800 border-gray-700 p-2 mx-2 max-[480px]:mb-8 mb-4">
    <h5
      class="mb-2 text-2xl font-bold tracking-tight text-white"
    >
      {{ article.titre | raw }} 
      {# striptags for the ... #}
    </h5>
    <div class="p-5 border-t-2 border-t-gray-950">
      <img class="rounded-t-lg" src="{{ vich_uploader_asset(article) }}" />
      <p class="mb-3 font-normal text-gray-400">
        <div class="border-t-2 border-t-gray-950 text-gray-400">
        {{ article.resume | raw }}
        </div>
      </p>
    </div>
  </div>
  {% endfor %}
</div>
</div>
{% include "footer/footer.html.twig" %} {% endblock %}